local M = {}

M.CANONICAL = {
  "LociInit",
  "LociHealth",
  "LociDoctor",
  "LociOpenRoot",
  "LociRepairFrontmatter",
  "LociRepairProjectRefs",
  "LociRefresh",
  "LociJobCancel",
  "LociJobList",
  "LociTrailList",
  "LociTrailCreate",
  "LociTrailSwitch",
  "LociTrailSave",
  "LociTrailLoad",
  "LociTrailRename",
  "LociTrailDelete",
  "LociTrailExport",
  "LociWorkspaceSwitch",
  "LociRepositoryOpen",
  "LociWorkspaceCreate",
  "LociWorkspaceClone",
  "LociKnowledgeAdd",
  "LociKnowledgeRemove",
  "LociKnowledgeSetPrimary",
  "LociFileLink",
  "LociFileUnlink",
  "LociWorkspaceInfo",
  "LociWorkspaceArchive",
  "LociWorkspaceRefresh",
  "LociNoteCreate",
  "LociDailyNote",
  "LociScratchNote",
  "LociNoteAdopt",
  "LociHauntList",
  "LociHauntNew",
  "LociHauntSwitch",
  "LociHauntRename",
  "LociHauntDelete",
  "LociProjectCreate",
  "LociProjectOpen",
  "LociProjectSwitch",
  "LociProjectLink",
  "LociProjectInfo",
  "LociProjectRefresh",
}

M.FORBIDDEN = {
  "LociTaskComplete",
  "LociTaskArchive",
  "LociIssueResolve",
  "LociProjectDone",
  "LociProjectNew",
  "LociProjectPicker",
  "LociProjectLinkCurrent",
  "LociWorkspaceNew",
  "LociWorkspaceOpen",
  "LociWorkspacePicker",
  "LociWorkspaceAddKnowledge",
  "LociWorkspaceRemoveKnowledge",
  "LociWorkspaceSetPrimary",
  "LociWorkspaceLinkCurrentFile",
  "LociWorkspaceUnlinkCurrentFile",
  "LociTrailNew",
  "LociTrailExportQuickfix",
  "LociTaskNotesBrowse",
  "LociTaskNotesNew",
  "LociTaskNotesEdit",
  "LociTaskNotesRescan",
  "LociTaskNotesView",
  "LociNoteNew",
}

return M
