local helpers = require("tests.helpers")
local MiniTest = require("mini.test")
local expect = MiniTest.expect

local T = MiniTest.new_set()

T["bases default_specs returns six filenames"] = helpers.async_test(function()
  local bases = require("loci.service.bases")
  local specs = bases.default_specs()
  expect.equality(#specs, 6)

  local filenames = {}
  for _, spec in ipairs(specs) do
    table.insert(filenames, spec.filename)
  end
  table.sort(filenames)

  expect.equality(filenames[1], "loci-daily.base")
  expect.equality(filenames[2], "loci-issues.base")
  expect.equality(filenames[3], "loci-notes.base")
  expect.equality(filenames[4], "loci-open-work.base")
  expect.equality(filenames[5], "loci-projects.base")
  expect.equality(filenames[6], "loci-tasks.base")
end)

T["bases serialize includes generated-file header"] = helpers.async_test(function()
  local bases = require("loci.service.bases")
  local spec = {
    filename = "test.base",
    filters = { ["and"] = { "note.type == \"task\"" } },
    views = {
      {
        type = "table",
        name = "Test View",
        filters = { ["and"] = { "note.type == \"task\"" } },
        order = { "title" },
        sort = { { column = "title", direction = "ASC" } },
      },
    },
  }

  local r = bases.serialize(spec)
  helpers.expect_ok(r)
  local content = r.value

  expect.equality(content:find("Generated by LOCI") ~= nil, true)
  expect.equality(content:find("Markdown files under") ~= nil, true)
end)

T["bases serialize is deterministic"] = helpers.async_test(function()
  local bases = require("loci.service.bases")
  local spec = {
    filename = "test.base",
    filters = { ["and"] = { "note.type == \"task\"" } },
    views = {
      {
        type = "table",
        name = "Tasks",
        filters = { ["and"] = { "note.type == \"task\"" } },
        order = { "file.name", "title" },
        sort = { { column = "title", direction = "ASC" } },
      },
    },
  }

  local r1 = bases.serialize(spec)
  local r2 = bases.serialize(spec)

  expect.equality(r1.value, r2.value)
end)

T["bases regenerate writes all default files"] = helpers.async_test(function()
  local repo = helpers.create_tmpdir()
  local restore = helpers.patch_project_root(repo)
  helpers.reset_modules()

  require("loci").setup({
    integrations = { bases = true },
    refresh = { on_setup = false },
  })

  local init_r = require("loci.service.repository").init({ now = "2026-05-23T12:00:00-04:00" })
  helpers.expect_ok(init_r)

  local bases = require("loci.service.bases")
  local r = bases.regenerate({ now = "2026-05-23T12:00:00-04:00" })
  local value = helpers.expect_ok(r)

  expect.equality(value.enabled, true)
  expect.equality(#value.files, 6)

  -- Verify all files exist
  for _, file in ipairs(value.files) do
    expect.equality(vim.fn.filereadable(file.path), 1)
  end

  restore()
  helpers.remove_tmpdir(repo)
end)

T["bases generated files contain views and filters"] = helpers.async_test(function()
  local repo = helpers.create_tmpdir()
  local restore = helpers.patch_project_root(repo)
  helpers.reset_modules()

  require("loci").setup({
    integrations = { bases = true },
    refresh = { on_setup = false },
  })

  local init_r = require("loci.service.repository").init({ now = "2026-05-23T12:00:00-04:00" })
  helpers.expect_ok(init_r)

  local bases = require("loci.service.bases")
  local r = bases.regenerate({ now = "2026-05-23T12:00:00-04:00" })
  local value = helpers.expect_ok(r)

  for _, file in ipairs(value.files) do
    local f = io.open(file.path, "r")
    local content = f:read("*a")
    f:close()

    expect.equality(content:find("views:") ~= nil, true)
    expect.equality(content:find("filters:") ~= nil, true)
  end

  restore()
  helpers.remove_tmpdir(repo)
end)

T["bases files do not contain graph json paths"] = helpers.async_test(function()
  local repo = helpers.create_tmpdir()
  local restore = helpers.patch_project_root(repo)
  helpers.reset_modules()

  require("loci").setup({
    integrations = { bases = true },
    refresh = { on_setup = false },
  })

  local init_r = require("loci.service.repository").init({ now = "2026-05-23T12:00:00-04:00" })
  helpers.expect_ok(init_r)

  local bases = require("loci.service.bases")
  local r = bases.regenerate({ now = "2026-05-23T12:00:00-04:00" })
  local value = helpers.expect_ok(r)

  for _, file in ipairs(value.files) do
    local f = io.open(file.path, "r")
    local content = f:read("*a")
    f:close()

    expect.equality(content:find("%.loci/graph") ~= nil, false)
    expect.equality(content:find("%.loci/indexes") ~= nil, false)
    expect.equality(content:find("project_id") ~= nil, false)
    expect.equality(content:find("workspace_id") ~= nil, false)
  end

  restore()
  helpers.remove_tmpdir(repo)
end)

T["bases disabled returns skipped result"] = helpers.async_test(function()
  local repo = helpers.create_tmpdir()
  local restore = helpers.patch_project_root(repo)
  helpers.reset_modules()

  require("loci").setup({
    integrations = { bases = false },
    refresh = { on_setup = false },
  })

  local init_r = require("loci.service.repository").init({ now = "2026-05-23T12:00:00-04:00" })
  helpers.expect_ok(init_r)

  local bases = require("loci.service.bases")
  local r = bases.regenerate({ now = "2026-05-23T12:00:00-04:00" })
  local value = helpers.expect_ok(r)

  expect.equality(value.enabled, false)
  expect.equality(value.status, "disabled")

  restore()
  helpers.remove_tmpdir(repo)
end)

T["bases available checks bases.nvim not config"] = helpers.async_test(function()
  local bases = require("loci.service.bases")
  local available = bases.available()
  expect.equality(type(available), "boolean")
  -- Don't assert true or false - just check it's a boolean
end)

T["bases health reports structure"] = helpers.async_test(function()
  local bases = require("loci.service.bases")
  local health = bases.health()
  expect.no_equality(health, nil)
  expect.equality(type(health), "table")
  expect.equality(health.name, "bases")
  expect.equality(type(health.available), "boolean")
  expect.equality(type(health.enabled), "boolean")
end)

return T
