local MiniTest = require('mini.test')
local expect = MiniTest.expect

local T = MiniTest.new_set()

local id = require('loci.domain.id')

T['slugify() lowercases'] = function()
  expect.equality(id.slugify('Hello World'), 'hello-world')
end

T['slugify() replaces spaces with hyphens'] = function()
  expect.equality(id.slugify('fix parser edge case'), 'fix-parser-edge-case')
end

T['slugify() removes special characters'] = function()
  expect.equality(id.slugify('Hello, World! (v2)'), 'hello-world-v2')
end

T['slugify() collapses multiple hyphens'] = function()
  expect.equality(id.slugify('a---b'), 'a-b')
end

T['slugify() strips leading hyphens'] = function()
  expect.equality(id.slugify('--leading'), 'leading')
end

T['slugify() strips trailing hyphens'] = function()
  expect.equality(id.slugify('trailing--'), 'trailing')
end

T['slugify() handles nil'] = function()
  expect.equality(id.slugify(nil), '')
end

T['slugify() handles empty string'] = function()
  expect.equality(id.slugify(''), '')
end

T['slugify() handles only special characters'] = function()
  expect.equality(id.slugify('!@#$%'), '')
end

T['slugify() handles mixed whitespace'] = function()
  expect.equality(id.slugify('hello\t  world\n'), 'hello-world')
end

T['slugify() preserves numbers'] = function()
  expect.equality(id.slugify('Version 3 Beta'), 'version-3-beta')
end

T['short_id() returns string of default length 6'] = function()
  local sid = id.short_id()
  expect.equality(type(sid), 'string')
  expect.equality(#sid, 6)
end

T['short_id() respects custom length'] = function()
  expect.equality(#id.short_id(10), 10)
  expect.equality(#id.short_id(1), 1)
end

T['short_id() contains only valid characters'] = function()
  for _ = 1, 20 do
    local sid = id.short_id()
    expect.equality(sid:match('^[a-z0-9]+$') ~= nil, true)
  end
end

T['short_id() generates different values'] = function()
  local seen = {}
  for _ = 1, 50 do
    local sid = id.short_id()
    seen[sid] = true
  end
  local count = 0
  for _ in pairs(seen) do count = count + 1 end
  expect.equality(count > 40, true)
end

T['new() returns slug-shortid format'] = function()
  local generated = id.new('Fix parser edge case')
  expect.equality(generated:match('^fix%-parser%-edge%-case%-[a-z0-9]+$') ~= nil, true)
end

T['new() generates unique IDs'] = function()
  local a = id.new('Test')
  local b = id.new('Test')
  expect.no_equality(a, b)
end

T['new() handles empty title with untitled fallback'] = function()
  local generated = id.new('')
  expect.equality(generated:match('^untitled%-[a-z0-9]+$') ~= nil, true)
end

T['new() handles special-chars-only title with untitled fallback'] = function()
  local generated = id.new('!@#$%')
  expect.equality(generated:match('^untitled%-[a-z0-9]+$') ~= nil, true)
end

T['is_valid() accepts valid IDs'] = function()
  expect.equality(id.is_valid('fix-parser-edge-case-a1b2c3'), true)
  expect.equality(id.is_valid('loci-v3-redesign-abc123'), true)
  expect.equality(id.is_valid('a-abc123'), true)
end

T['is_valid() rejects IDs without slug and short-id'] = function()
  expect.equality(id.is_valid('abc123'), false)
  expect.equality(id.is_valid('a'), false)
end

T['is_valid() rejects nil'] = function()
  expect.equality(id.is_valid(nil), false)
end

T['is_valid() rejects empty string'] = function()
  expect.equality(id.is_valid(''), false)
end

T['is_valid() rejects path traversal'] = function()
  expect.equality(id.is_valid('..'), false)
  expect.equality(id.is_valid('foo/../bar'), false)
end

T['is_valid() rejects path separators'] = function()
  expect.equality(id.is_valid('foo/bar'), false)
  expect.equality(id.is_valid('foo\\bar'), false)
end

T['is_valid() rejects uppercase'] = function()
  expect.equality(id.is_valid('Hello'), false)
end

T['is_valid() rejects leading hyphen'] = function()
  expect.equality(id.is_valid('-foo'), false)
end

T['is_valid() rejects trailing hyphen'] = function()
  expect.equality(id.is_valid('foo-'), false)
end

T['is_valid() rejects special characters'] = function()
  expect.equality(id.is_valid('foo-abc'), false)
  expect.equality(id.is_valid('foo-abcdefg'), false)
  expect.equality(id.is_valid('Foo-abcdef'), false)
  expect.equality(id.is_valid('foo--bar-abcdef'), false)
  expect.equality(id.is_valid('foo-bar--abcdef'), false)
  expect.equality(id.is_valid('foo_bar'), false)
  expect.equality(id.is_valid('foo.bar'), false)
  expect.equality(id.is_valid('foo bar'), false)
end

T['is_valid() accepts IDs generated by new()'] = function()
  for _ = 1, 10 do
    local generated = id.new('Some Test Title')
    expect.equality(id.is_valid(generated), true)
  end
end

T['short_id() supports minimum custom length'] = function()
  expect.equality(#id.short_id(1), 1)
end

return T
