"""Example agent: Add docstrings to Python functions.

This is an example of agent code that would be generated by the LLM.
It demonstrates:
- Using search_files to find Python files
- Reading file contents
- Using ask_llm for code generation
- Writing modified files
- Submitting results
"""

# Find all Python files
files = search_files("*.py")
changed_files = []

for file_path in files:
    # Read file content
    content = read_file(file_path)

    # Check if file has functions without docstrings
    if "def " in content and '"""' not in content:
        log(f"Processing {file_path}")

        # Ask LLM to add docstrings
        prompt = "Add docstrings to all functions in this Python file"
        new_content = ask_llm(prompt, content)

        # Write modified file to overlay
        write_file(file_path, new_content)
        changed_files.append(file_path)
        log(f"Added docstrings to {file_path}")

# Submit result
if changed_files:
    submit_result(f"Added docstrings to {len(changed_files)} files", changed_files)
else:
    submit_result("No files needed docstrings", [])
